### ISSUE TITLE
Unable to update package in meteor project

### ISSUE THREAD

**Issue by MastaBaba** [meteor/mobile-packages#102]
When running "meteor update", I get the following:

The following top-level dependencies were not updated to the very latest version available:
 * mdg:camera 1.2.0 (1.3.0 is available)  

When running "meteor add mdg:camera@1.3.0" I get:

 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint isobuild:cordova@5.4.0 is not satisfied by isobuild:cordova
5.2.0.
Constraints on package "isobuild:cordova":
* isobuild:cordova@5.4.0 <- mdg:camera 1.3.0

How to get my mdg:camera package from 1.2.0 to 1.3.0?

**Comment by DavidSunny** [comment]
+1

**Comment by philthom** [comment]
+1

**Comment by josejuanisaac** [comment]
+1

**Comment by jessonjoy** [comment]
+1

**Comment by cpalanzo** [comment]
+1

**Comment by lucatros** [comment]
Are you building the package locally? I had this problem only when building it locally and changing the following line on ``package.js`` did the trick:
``  api.use("isobuild:cordova@5.2.0");``

**Comment by MastaBaba** [comment]
@lucatros I don't think I follow your suggestion. This is the package.js of mdg:camera? Shouldn't this be resolved on the package side without me having to make any changes?

I notice that sspatank committed a fix, yet, I still have the same issue.

**Comment by lucatros** [comment]
Sorry if I wasn't clear. As you mentioned, the issue should be solved on this repo and not on your side. In fact, @sspatank already fixed it but his pull request still has to be merged. 

Until the package is updated on this repo, you can just download all the files for this repo and place them inside the ``/packages`` folder, change the ``package.js`` file as mentioned on my comment above and then add the package as you would normally do (``meteor add mdg:camera``).  This will build the package locally. Note that if the package is updated, you won't get the updates because you are using a local copy of the package. Once package is updated you can delete your local copy on the ``/packages`` folder,  then ``meteor remove mdg:camera`` and finally run ``meteor add mdg:camera`` to add the package from this repo.

**Comment by perak** [comment]
@MastaBaba fixed. Thanks @lucatros & @sspatank

**Comment by philthom** [comment]
Same applies to mdg:geolocation

**Comment by cpalanzo** [comment]
remove mdg:geolocationadd mdg:geolocation
Still getting new version notice.
On update still getting:
While selecting package versions:error: Conflict: Constraint isobuild:cordova@5.4.0 is not satisfied byisobuild:cordova 5.2.0.Constraints on package "isobuild:cordova":* isobuild:cordova@5.4.0 <- mdg:geolocation 1.2.0   ----------------------------------------------------------------------------------------- "Everyone has a plan 'till they get punched in the mouth!" - M. Tyson

**Comment by MastaBaba** [comment]
It's fixed for me (for mdg:camera).

**Comment by perak** [comment]
@cpalanzo oops, I didn't changed mdg:geolocation version number (it's 1.2.0, should be 1.2.1). Will fix that soon.

**Comment by perak** [comment]
Fixed, but I cannot publish mdg:geolocation package... or can I? @stubailo ?

<img width="566" alt="screen shot 2016-02-16 at 1 58 40 pm" src="https://cloud.githubusercontent.com/assets/5630814/13076881/9e2c5bea-d4b5-11e5-8557-891dd138ffcb.png">

**Comment by tsega** [comment]
The issue still stands, I get the following error while trying to update the `mdg:geolocation` package to version `1.2.0`. (I have also tried removing and adding the package again)

```
$ meteor add mdg:geolocation@1.2.0
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint isobuild:cordova@5.4.0 is not satisfied by isobuild:cordova 5.2.0.
Constraints on package "isobuild:cordova":
* isobuild:cordova@5.4.0 <- mdg:geolocation 1.2.0
```

**Comment by perak** [comment]
@tsega if you clone package locally into your app's /packages dir it will work. Issue is fixed but I don't have access rights to publish mdg:geolocation package

**Comment by martijnwalraven** [comment]
The issue here is that plugin versions sometimes only work with certain Cordova versions. So the `isobuild:cordova` constraint is there to ensure we don't try to install a newer version of the plugin in a Meteor project with an older version of Cordova. That is what went wrong in https://github.com/meteor/mobile-packages/issues/110 for instance, so then you get a compile time or run time error.

In this case, I think it is indeed safe to change the constraint back to `isobuild:cordova@5.2.0`. I've published a new version and it should now work again with Meteor 1.2.
